# Generated by Django 4.0.6 on 2022-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_new_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
